version: '2'

services:
  db: 
    image: redis
    ports:
         - "6379"

  web:
    build: .
    command: node app.js
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      